SELECT i.ANIMAL_ID, i.NAME
FROM ANIMAL_INS i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID
GROUP BY o.DATETIME - i.DATETIME 
ORDER BY o.DATETIME - i.DATETIME DESC
LIMIT 2;

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS AS A
JOIN ANIMAL_INS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.DATETIME - B.DATETIME DESC
LIMIT 2;

SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
JOIN ANIMAL_INS B
USING (ANIMAL_ID) # 괄호 필수!
ORDER BY A.DATETIME - B.DATETIME DESC
LIMIT 2;