SELECT CAST(SUBSTR(DATETIME, 12, 2) as unsigned) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
WHERE 9 <= SUBSTR(DATETIME, 12, 2)
AND SUBSTR(DATETIME, 12, 2) <= 19
GROUP BY SUBSTR(DATETIME, 12, 2)
ORDER BY HOUR;

SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR
ORDER BY HOUR;

SELECT HOUR(DATETIME) HOUR, COUNT(DATETIME) COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR;
# 다시 풀기