set @hour := -1; # 방법1
select(@hour := @hour + 1) HOUR,
(SELECT COUNT(*) from ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;

WITH RECURSIVE ALL_HR AS( # 방법2
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM ALL_HR
    WHERE HOUR < 23
)

SELECT HOUR, IFNULL(AO.COUNT, 0) AS COUNT
FROM ALL_HR
LEFT OUTER JOIN (
    SELECT HOUR(DATETIME) HOUR, COUNT(*) COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
) AO
USING (HOUR);

WITH RECURSIVE ALL_HR AS( # 방법3
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HR
    WHERE HR < 23
)

SELECT A.HOUR, COUNT(HOUR(B.DATETIME)) COUNT
FROM ALL_HR A
LEFT JOIN ANIMAL_OUTS B
ON A.HOUR = HOUR(B.DATETIME)
GROUP BY A.HOUR;

# 다시 풀기