# 다시 풀기

SELECT ANIMAL_ID, NAME, IF(INSTR(SEX_UPON_INTAKE, 'Intact') > 0, 'X', 'O') '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME, 
CASE WHEN SEX_UPON_INTAKE IN('Intact MALE','Intact FEMALE') THEN 'X' ELSE 'O' END '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

SELECT ANIMAL_ID, NAME,
    REGEXP_REPLACE
    (REGEXP_REPLACE(SEX_UPON_INTAKE, 'Neutered Male|Spayed Female', 'O'), 
    'Intact Male|Intact Female', 'X') '중성화'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;